# Generated by Django 3.2.13 on 2023-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nickname', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=3)),
                ('age', models.CharField(max_length=3)),
                ('money', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=15)),
                ('bank', models.CharField(choices=[('KEB하나은행', 'KEB하나은행'), ('SC제일은행', 'SC제일은행'), ('국민은행', '국민은행'), ('신한은행', '신한은행'), ('외환은행', '외환은행'), ('우리은행', '우리은행'), ('한국시티은행', '한국시티은행'), ('경남은행', '경남은행'), ('광주은행', '광주은행'), ('부산은행', '부산은행'), ('전북은행', '전북은행'), ('제주은행', '제주은행'), ('기업은행', '기업은행'), ('농협', '농협'), ('수협', 'SC제일은행'), ('한국산업은행', '한국산업은행'), ('한국수출입은행', '한국수출입은행'), ('기타', '기타')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
