# Generated by Django 3.2.13 on 2023-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='financial_products',
            field=models.ManyToManyField(blank=True, null=True, to='api.Subscribe_Products'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_financial_products',
            field=models.ManyToManyField(blank=True, null=True, to='api.Like_Products'),
        ),
    ]
